FROM golang:latest

ARG TINI_VERSION=v0.18.0

RUN apt-get update -qq

RUN apt-get install -y vim

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable
    
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

COPY ./fonts/* /usr/share/fonts/truetype/

RUN mkdir -p /go

WORKDIR /go

ENTRYPOINT ["/tini", "--"]
